version: "3"
services:
  lake:
    container_name: lake
    name: lake
    restart: always
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - lake-network
  mongodb:
    image: mongo:5.0.0
    name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lake
      - MONGO_INITDB_ROOT_PASSWORD=lakeIScoming
    volumes:
      - ./data:/data/db
    ports:
      - 127.0.0.1:27017:27017
    restart: always
    networks:
      - lake-network
  postgresdb:
    image: postgres:13
    name: postgresdb
    environment:
      - POSTGRES_DB=lake
      - POSTGRES_PASSWORD=postgresWhat
      - POSTGRES_USER=postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - lake-network
  rabbitmq:
    image: rabbitmq:3-management
    name: rabbitmq
    ports:
      - 127.0.0.1:15672:15672
      - 127.0.0.1:5672:5672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: always
    networks:
      - lake-network
  grafana:
    image: grafana/grafana:8.0.6
    name: grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_JSON_ENABLED=true
    ports:
      - 3002:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./src/img/grafana_icon.svg:/usr/share/grafana/public/img/grafana_icon.svg:rw
    restart: always
    networks:
      - lake-network
volumes:
  grafana-storage: {}
networks:
  lake-network:
    driver: bridge